### ISSUE TITLE
Making code clean and removing unnecessary variables

### ISSUE THREAD

**Issue by imxitiz** [subashsigdel/AI#1]
From [/AI/tree/master/setopati_news_scraping](https://github.com/subash-5/AI/tree/master/setopati_news_scraping) directory all ipython file's second cell can be changes into 
```
# from bs4 import BeautifulSoup
# import requests
# You don't have to import these libary cuz u had already imported these libary in first cell.
import re
final_news = []
for i in links:
    response = requests.get(i)
    data = BeautifulSoup(response.content,'lxml')
    raw_data = data.find("div", class_="editor-box")
    raw_string = raw_data.text
    final=re.sub(r"""[\n%$”’&“\xa0;:?—\'s"-]""","",raw_string)
    final_news.append(final.strip())
final_news
```

> It is easy to do replacing in re. You can take a look at [re documentation](https://docs.python.org/3/library/re.html) for more details.

> final.strip() is especially for entertainment categories news. This will remove all first and last spaces. 
Like as "    Test news.  " will change into "Test news." after using string.strip()

**Comment by subashsigdel** [comment]
thankyou for the information
